name: Deploy to AWS EC2 backend-uas

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2 backend
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@47.129.255.172 << 'EOF'
            sudo docker pull fahdira/backend-uas
            sudo docker stop backend || true && sudo docker rm backend || true
            sudo docker run -d --name backend -p 8080:8080 --env-file /home/ec2-user/.env fahdira/backend-uas
          EOF
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
